spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loans
    username: kariuki
    password: Password1!
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 5005
application:
  config:
    interest-rate: 0.18
    accounts-url: http://localhost:8888/api/v2/accounts
    transactions-url: http://localhost:8888/api/v2/transactions